/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v2/auth/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        platform?: "ios" | "android" | "web";
                        provider: "google" | "apple";
                        token: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            exists: boolean;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/auth/email/verification-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SendAuthCodeResponseDTOSchema"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/auth/email/verification-codes/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        authCode: string;
                        /** Format: email */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfirmAuthCodeResponseDTOSchema"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                        password?: string;
                        platform?: "android" | "ios" | "web";
                        provider: "google" | "apple" | "email";
                        token?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserWithAuthTokenDTOSchema"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/auth/tokens/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReissueTokenBodyDTOSchemaInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserWithAuthTokenDTOSchema"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        email: string;
                        marketingConsent?: boolean;
                        nightMarketingConsent?: boolean;
                        password?: string;
                        platform?: "android" | "ios" | "web";
                        provider: "google" | "apple" | "email";
                        termsVersionIds?: string[];
                        token?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserWithAuthTokenDTOSchema"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/events/upload-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PresignPostBodyDTOSchemaInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PresignedPostDTOSchema"];
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponseDTOSchema"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ConfirmAuthCodeResponseDTOSchema: {
            /** Format: email */
            email: string;
        };
        ErrorResponseDTOSchema: {
            code: "INVALID_ANONYMOUS_USER" | "INVALID_PASSWORD" | "INVALID_ACCESS_TOKEN" | "INVALID_QUERY_STRING" | "USER_NOT_FOUND" | "CONCERT_NOT_FOUND" | "SUBSCRIBED_CONCERT_NOT_FOUND" | "ARTIST_NOT_FOUND" | "VENUE_NOT_FOUND" | "SUBSCRIBED_ARTIST_NOT_FOUND" | "SUBSCRIBED_VENUE_NOT_FOUND" | "INVALID_USER" | "PASSWORD_NOT_MATCH" | "ACCESS_TOKEN_NOT_FOUND" | "USER_DEACTIVATED" | "USER_ALREADY_EXISTING" | "EMAIL_AUTH_REQUEST_NOT_FOUND" | "INVALID_EMAIL_AUTH_REQUEST" | "EMAIL_AUTH_REQUEST_ALREADY_AUTHENTICATED" | "EMAIL_AUTH_REQUEST_TIMEOUT" | "UNKNOWN" | "EVENT_NOT_FOUND" | "POSTER_NOT_FOUND" | "ARTIST_PROFILE_IMAGE_NOT_FOUND" | "IMAGE_KEY_NOT_FOUND" | "IMAGE_NOT_FOUND" | "REFRESH_TOKEN_NOT_FOUND" | "TICKET_NOT_FOUND" | "INVALID_ACTION_TOKEN" | "INVALID_GEO_DATA" | "INVALID_FEED_ENTITY_TYPE" | "INVALID_FEED" | "FEED_NOT_FOUND" | "INVALID_IMAGE_META" | "CONSENT_REQUIRED" | "PARTNER_NOT_FOUND" | "PARTNER_NOT_VERIFIED" | "PARTNER_ALREADY_EXISTS" | "NOT_CONNECTED_CONCERT" | "ENTRY_TICKETS_ALREADY_ISSUED" | "ENTRY_TICKET_NOT_FOUND" | "ENTRY_TICKET_ALREADY_USED" | "ENTRY_TICKET_NOT_CLAIMED" | "ENTRY_TICKET_ALREADY_CLAIMED" | "ENTRY_TICKET_SOLD_OUT" | "NEWSLETTER_SUBSCRIBER_NOT_FOUND" | "INVALID_TERMS_VERSION" | "TERMS_VERSION_NOT_FOUND" | "NOTIFICATION_NOT_FOUND" | "REVIEW_NOT_FOUND" | "REVIEW_ALREADY_EXISTS" | "REVIEW_FORBIDDEN" | "EVENT_NOT_ENDED" | "COMMENT_NOT_FOUND" | "COMMENT_FORBIDDEN";
            message: string;
        };
        PresignedPostDTOSchema: {
            fields: {
                [key: string]: string;
            };
            url: string;
        };
        PresignPostBodyDTOSchema: {
            concertId: string;
            /** @enum {string} */
            resolution: "low" | "medium" | "high";
            /** @enum {string} */
            type: "poster" | "detail-image";
        };
        PresignPostBodyDTOSchemaInput: {
            concertId: string;
            /** @enum {string} */
            resolution: "low" | "medium" | "high";
            /** @enum {string} */
            type: "poster" | "detail-image";
        };
        ReissueTokenBodyDTOSchemaInput: {
            refreshToken: string;
        };
        SendAuthCodeResponseDTOSchema: {
            /** Format: email */
            email: string;
        };
        UserDTOSchema: {
            deactivatedAt: string | null;
            email: string;
            handle: components["schemas"]["UserHandleDTOSchema"] | null;
            id: string;
            meta?: {
                consentRequired: boolean;
            };
            provider: string;
        };
        UserHandleDTOSchema: string;
        UserWithAuthTokenDTOSchema: {
            authToken: {
                accessToken: string;
                refreshToken: string;
            };
            user: components["schemas"]["UserDTOSchema"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
