import { z } from 'zod'

export const ErrorCodeSchema = z.union([
  z.literal('INVALID_ANONYMOUS_USER'),
  z.literal('INVALID_PASSWORD'),
  z.literal('INVALID_ACCESS_TOKEN'),
  z.literal('INVALID_QUERY_STRING'),
  z.literal('USER_NOT_FOUND'),
  z.literal('CONCERT_NOT_FOUND'),
  z.literal('SUBSCRIBED_CONCERT_NOT_FOUND'),
  z.literal('ARTIST_NOT_FOUND'),
  z.literal('VENUE_NOT_FOUND'),
  z.literal('SUBSCRIBED_ARTIST_NOT_FOUND'),
  z.literal('SUBSCRIBED_VENUE_NOT_FOUND'),
  z.literal('INVALID_USER'),
  z.literal('PASSWORD_NOT_MATCH'),
  z.literal('ACCESS_TOKEN_NOT_FOUND'),
  z.literal('USER_DEACTIVATED'),
  z.literal('USER_ALREADY_EXISTING'),
  z.literal('HANDLE_RESERVED'),
  z.literal('EMAIL_AUTH_REQUEST_NOT_FOUND'),
  z.literal('INVALID_EMAIL_AUTH_REQUEST'),
  z.literal('EMAIL_AUTH_REQUEST_ALREADY_AUTHENTICATED'),
  z.literal('EMAIL_AUTH_REQUEST_TIMEOUT'),
  z.literal('UNKNOWN'),
  z.literal('EVENT_NOT_FOUND'),
  z.literal('POSTER_NOT_FOUND'),
  z.literal('ARTIST_PROFILE_IMAGE_NOT_FOUND'),
  z.literal('IMAGE_KEY_NOT_FOUND'),
  z.literal('IMAGE_NOT_FOUND'),
  z.literal('REFRESH_TOKEN_NOT_FOUND'),
  z.literal('TICKET_NOT_FOUND'),
  z.literal('INVALID_ACTION_TOKEN'),
  z.literal('INVALID_GEO_DATA'),
  z.literal('INVALID_FEED_ENTITY_TYPE'),
  z.literal('INVALID_FEED'),
  z.literal('FEED_NOT_FOUND'),
  z.literal('INVALID_IMAGE_META'),
  z.literal('CONSENT_REQUIRED'),
  z.literal('PARTNER_NOT_FOUND'),
  z.literal('PARTNER_NOT_VERIFIED'),
  z.literal('PARTNER_ALREADY_EXISTS'),
  z.literal('NOT_CONNECTED_CONCERT'),
  z.literal('ENTRY_TICKETS_ALREADY_ISSUED'),
  z.literal('ENTRY_TICKET_NOT_FOUND'),
  z.literal('ENTRY_TICKET_ALREADY_USED'),
  z.literal('ENTRY_TICKET_NOT_CLAIMED'),
  z.literal('ENTRY_TICKET_ALREADY_CLAIMED'),
  z.literal('ENTRY_TICKET_SOLD_OUT'),
  z.literal('NEWSLETTER_SUBSCRIBER_NOT_FOUND'),
  z.literal('INVALID_TERMS_VERSION'),
  z.literal('TERMS_VERSION_NOT_FOUND'),
  z.literal('NOTIFICATION_NOT_FOUND'),
  z.literal('REVIEW_NOT_FOUND'),
  z.literal('REVIEW_ALREADY_EXISTS'),
  z.literal('REVIEW_FORBIDDEN'),
  z.literal('EVENT_NOT_ENDED'),
  z.literal('COMMENT_NOT_FOUND'),
  z.literal('COMMENT_FORBIDDEN'),
  // 레이트 리밋 초과(429). 지금은 `POST /v2/data-correction-requests` 하나가 쓴다.
  z.literal('RATE_LIMITED'),
  // `/v1/daily/{series}/{slug}` — 그 시리즈에 그 slug 의 편이 없다.
  z.literal('DAILY_EDITION_NOT_FOUND'),
])

export const ErrorResponseDTOSchema = z.object({
  code: ErrorCodeSchema,
  message: z.string(),
})

export type ErrorResponseDTO = z.infer<typeof ErrorResponseDTOSchema>
